[k3s_control]
k3s-control-01 ansible_host=192.168.50.147

[k3s_workers]
k3s-worker-01 ansible_host=192.168.50.132
k3s-worker-02 ansible_host=192.168.50.110

[k3s_cluster:children]
k3s_control
k3s_workers
