---
- name: Run preflight checks
  ansible.builtin.import_playbook: preflight.yml

- name: Bootstrap Ubuntu nodes
  ansible.builtin.import_playbook: bootstrap.yml

- name: Install k3s cluster
  ansible.builtin.import_playbook: install-k3s.yml

- name: Check cluster status
  ansible.builtin.import_playbook: cluster-status.yml

- name: Install Flux GitOps
  ansible.builtin.import_playbook: install-flux.yml

- name: Check cluster status
  ansible.builtin.import_playbook: cluster-status.yml

- name: Check storage status
  ansible.builtin.import_playbook: storage-status.yml
